version: '3'

services:
  client:
    build:
      context: client-side
    volumes:
      - ./client-side:/usr/src/app
    ports:
      - 3000:3000
  api:
    build:
      context: web-api
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 8080 -b '0.0.0.0'"
    ports:
      - 8080:8080
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - ./web-api:/usr/src/app
  db:
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
